# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0b94d03
_src_path: gh:scipp/copier_template
description: Neutron scattering tools for Data Reduction
max_python: '3.11'
min_python: '3.9'
namespace_package: ''
nightly_deps: scipp,scippnexus,plopp
orgname: scipp
prettyname: ScippNeutron
projectname: scippneutron
related_projects: Scipp,ScippNexus,Plopp
year: 2023
