# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: ec3c4a2
_src_path: gh:scipp/copier_template
description: Neutron scattering tools for Data Reduction
max_python: '3.12'
min_python: '3.10'
namespace_package: ''
nightly_deps: scipp,scippnexus,plopp,mpltoolbox,sciline,tof
orgname: scipp
prettyname: ScippNeutron
projectname: scippneutron
related_projects: Scipp,ScippNexus,Plopp
year: 2024
