package:
  name: scippneutron
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - cmake
    - conan
    - gxx_linux-64 11.1.* [linux64]
    - git
    - ninja
    - python {{ python }}
    - scipp::scipp {{ scipp }}
    - tbb-devel
    # doc build requirements
    - appdirs
    - graphlib-backport # for python < 3.9
    - h5py
    - ipykernel=6.3.1  # issue with pythreejs 3d plotting, see https://github.com/ipython/ipykernel/issues/771
    - ipympl
    - ipywidgets
    - scipp::mantid-framework [not win]
    - matplotlib-base
    - nbsphinx
    - python-configuration
    - python-graphviz
    - pythreejs
    - pyyaml
    - scipy>=1.7.0
    - sphinx
    - sphinx-book-theme
    - sphinx-copybutton
  run:
    - pooch
    - python {{ python }}
    - scipp::scipp {{ scipp }}
    - h5py
    - scipy

test:
  imports:
    - scippneutron
  requires:
    - cmake
    - conan
    - gxx_linux-64 11.1.* [linux64]
    - h5py
    - ipykernel = 6.3.1  # see https://github.com/ipython/ipykernel/issues/771
    - ipympl
    - ipywidgets
    - matplotlib-base
    - psutil
    - pytest
    - pytest-asyncio
    - pythreejs
    - scipp::mantid-framework [not win]
    - tbb-devel
    - python-confluent-kafka [linux64]
    - ess-dmsc:ess-streaming-data-types [linux64]
    - requests
    - pandoc
    - sphinx
    - sphinx-book-theme
    - nbsphinx
    - python-graphviz
  files:
    - cmake-package-test/
  source_files:
    - tests/
    - docs/
    - .git/  # Docs build uses git to determine version and release month
  script_env:
    - DOCS_BUILD_DIR
  commands:
    - python -m pytest -v tests
    - python cmake-package-test/build.py
    - python docs/build_and_test.py [linux64]

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script_env:
    - OSX_VERSION [osx]
    - CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
  script:
    - python tools/build_cpp.py

about:
  home: https://github.com/scipp/scippneutron
  license: BSD-3-Clause
  summary: Neutron scattering tools for Data Reduction
  description: Neutron scattering tools for Data Reduction
  dev_url: https://github.com/scipp/scippneutron
  doc_url: https://scipp.github.io/scippneutron
