# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Scipp contributors (https://github.com/scipp)

# Note:
#
# The conda documentation recommends placing version number in the
# conda_build_config.yaml file, instead of directly in this meta.yaml file:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
# It seems the primary advantage of doing this is that it allows matrix builds from a
# single conda-build command.
# For now, the only matrix-style building we are doing is the python version,
# which is set via the `--python` command line argument anyway, because we are
# parallelising our CI builds.
# A matrix build from conda-build directly would have to perform the lib solving for
# each version, and using multiple workers on our CI is faster than building all python
# versions in a single conda-build step.

package:
  name: scippneutron
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - h5py
    - numpy>=1.20.0
    - pooch
    - python
    - scipp>=23.03.2
    - scippnexus>=23.03.0
    - scipy>=1.7.0

test:
  imports:
    - scippneutron
  requires:
    - hypothesis==6.71.0
    - ipympl==0.9.3
    - ipywidgets==8.0.6
    - markupsafe>=1.1.1,<2.1.0  # see https://github.com/pallets/markupsafe/issues/284
    - matplotlib-base==3.7.1
    - plopp==23.04.0
    - psutil==5.9.4
    - pytest==7.3.0
    - pytest-asyncio==0.21.0
    - pythreejs==2.4.2
    - mantid==6.6.0 [py==38]
    - python-confluent-kafka==1.9.2 [linux64]
    - ess-streaming-data-types==v0.14.0 [linux64]
  source_files:
    - tests/
  commands:
    - python -m pytest

build:
  ignore_run_exports:
    - mantid [py==38]
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/scippneutron
  license: BSD-3-Clause
  summary: Neutron scattering tools for Data Reduction
  description: Neutron scattering tools for Data Reduction
  dev_url: https://github.com/scipp/scippneutron
  doc_url: https://scipp.github.io/scippneutron
