package:
  name: scippneutron

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..


{% set pyproject = load_file_data('pyproject.toml') %}
{% set dependencies = pyproject.get('project', {}).get('dependencies', {}) %}


requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - python>=3.10

  {% for package in dependencies %}
    - {% if package == "graphviz" %}python-graphviz{% else %}{{ package }}{% endif %}
  {% endfor %}


test:
  imports:
    - scippneutron
  requires:
    - hypothesis==6.88.1
    - ipympl==0.9.3
    - ipywidgets==8.1.1
    - markupsafe>=1.1.1,<2.1.0  # see https://github.com/pallets/markupsafe/issues/284
    - matplotlib-base==3.8.0
    - plopp==24.05.0
    - psutil==5.9.5
    - pytest==7.4.2
    - pytest-asyncio==0.21.1
    - pythreejs==2.4.2
    - python-confluent-kafka==2.1.1 [linux64]
    - ess-streaming-data-types==v0.14.0 [linux64]
    - sciline==24.04.1
  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  ignore_run_exports:
    - mantid [py==310]
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/scippneutron
  license: BSD-3-Clause
  summary: Neutron scattering tools for Data Reduction
  description: Neutron scattering tools for Data Reduction
  dev_url: https://github.com/scipp/scippneutron
  doc_url: https://scipp.github.io/scippneutron
