package:
  name: scippneutron

  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..


{% set pyproject = load_file_data('pyproject.toml') %}
{% set dependencies = pyproject.get('project', {}).get('dependencies', {}) %}
{% set test_dependencies = pyproject.get('project', {}).get('optional-dependencies', {}).get('test', {}) %}


requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - python>=3.10

  {# Conda does not allow spaces between package name and version, so remove them #}
  {% for package in dependencies %}
    - {% if package == "graphviz" %}python-graphviz{% else %}{{ package|replace(" ", "") }}{% endif %}
  {% endfor %}


test:
  imports:
    - scippneutron
  requires:

  {# Conda does not allow spaces between package name and version, so remove them #}
  {% for package in test_dependencies %}
    - {% if package == "graphviz" %}python-graphviz{% else %}{{ package|replace(" ", "") }}{% endif %}
  {% endfor %}
    # Note that we add tof here because it depends on plopp, and plopp should not be in
    # basetest.in because of the nightly dependencies
    - tof

  source_files:
    - pyproject.toml
    - tests/
  commands:
    # We ignore warnings during release package builds
    - python -m pytest -Wignore tests

build:
  ignore_run_exports:
    - mantid [py==310]
  noarch: python
  script:
    - python -m pip install .

about:
  home: https://github.com/scipp/scippneutron
  license: BSD-3-Clause
  summary: Neutron scattering tools for Data Reduction
  description: Neutron scattering tools for Data Reduction
  dev_url: https://github.com/scipp/scippneutron
  doc_url: https://scipp.github.io/scippneutron
