parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scippneutron > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: env_file_from_conda_meta # refs/tags/4.0.0

trigger:
  tags:
    include:
      - '*.*.*'

schedules:
  - cron: "0 0 * * *"
    displayName: 'Nightly dev build'
    branches:
      include:
        - 'main'
    always: false


pr: none

extends:
  template: pipelines/stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: 'conda-forge,scipp,ess-dmsc'
    gh_pages_subdirectory: 'scippneutron'
    config:
      linux:
        py_versions: ['3.7', '3.8', '3.9']
      osx:
        py_versions: ['3.7', '3.8', '3.9']
      windows:
        py_versions: ['3.7', '3.8', '3.9']
    package: true
    deploy: true
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:  # nightly
      conda_label: 'dev'
    ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/main') }}:  # tagged release
      conda_label: 'main'
      release: true
