parameters:
- name: verbose
  displayName: Verbose
  type: boolean
  default: false

# Note: the 'endpoint' refers to the Azure service connection, which can be
# found on the Azure pipelines web interface under
# scipp > scippneutron > Settings > Service connections

resources:
  repositories:
  - repository: SharedPipelines
    name: scipp/pipelines
    type: github
    endpoint: scipp
    ref: main  # TODO: change to tag once new tag is created in pipelines repo

trigger:
  - main

pr:
  autoCancel: true
  branches:
    include:
      - '*'

extends:
  template: stages.yml@SharedPipelines
  parameters:
    verbose: ${{ parameters.verbose }}
    conda_channels: '--channel scipp --channel ess-dmsc'
    gh_pages_subdirectory: 'scippneutron'
    config:
      linux:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer.yml'
      osx:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer-osx.yml'
      windows:
        py_versions: ['3.7']
        conda_env: 'scippneutron-developer-no-mantid.yml'
