name: Test

on:
  workflow_dispatch:
    inputs:
      os-variant:
        default: 'ubuntu-24.04'
        type: string
      python-version:
        type: string
      tox-env:
        default: 'test'
        type: string
      pip-recipe:
        default: 'requirements/ci.txt'
        type: string
      coverage-report:
        default: false
        type: boolean
      checkout_ref:
        default: ''
        type: string
  workflow_call:
    inputs:
      os-variant:
        default: 'ubuntu-24.04'
        type: string
      python-version:
        type: string
      tox-env:
        default: 'test'
        type: string
      pip-recipe:
        default: 'requirements/ci.txt'
        type: string
      coverage-report:
        default: false
        type: boolean
      checkout_ref:
        default: ''
        type: string

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  package-test:
    runs-on: ${{ inputs.os-variant }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: python -m pip install --upgrade pip
      - run: python -m pip install .
      - run: python tests/package_test.py
        name: Run package tests

  test:
    runs-on: ${{ inputs.os-variant }}
    env:
        ESS_PROTECTED_FILESTORE_USERNAME: ${{ secrets.ESS_PROTECTED_FILESTORE_USERNAME }}
        ESS_PROTECTED_FILESTORE_PASSWORD: ${{ secrets.ESS_PROTECTED_FILESTORE_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout_ref }}
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
          cache: true
          products: "MATLAB_Compiler_SDK"
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: ci-test
          condarc: |
            channels:
              - mantid
              - conda-forge
          create-args: >-
            python=${{ inputs.python-version }}
            mantid=6.11.0
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r ${{ inputs.pip-recipe }}
      - run: python -m pip install -r requirements/test.txt
      - run: pip install --no-build-isolation --no-deps -e .
      - run: tox -e ${{ inputs.tox-env }} --current-env
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.coverage-report }}
        with:
          name: CoverageReport
          path: coverage_html/
